import os
ecutwfcs = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

main_dir = 'protocol_ecutwfc'
os.mkdir(main_dir)

for e in range(len(ecutwfcs)):
    file_path = os.path.join(main_dir, f'system_ecut_{ecutwfcs[e]}.in')
    with open(file_path, 'w') as file:
        file.write('&control\n')
        file.write('   calculation  = \'scf\'\n')
        file.write('   title        = \'\'\n')
        file.write('   tstress      = .FALSE.\n')
        file.write('   tprnfor      = .TRUE.\n')
        file.write('   prefix       = \'pwscf\'\n')
        file.write(' /\n')
        file.write(' &system\n')
        file.write('    ibrav       = \n')
        file.write('    a           = \n')
        file.write('    b           = \n')
        file.write('    c           = \n')
        file.write('    nat         = \n')
        file.write('    ntyp        = \n')
        file.write(f'    ecutwfc    = {ecutwfcs[e]} \n')
        file.write(f'    ecutrho    = {8*ecutwfcs[e]} \n')
        file.write('    nosym       = .TRUE.\n')
        file.write('    occupations = \'smearing\'\n')
        file.write('    degauss     = 0.02D0\n')
        file.write('    smearing    = \'mp\'\n')
        file.write('    nspin       = \n')
        file.write('    starting_magnetization(1) =  \n')
        file.write('    starting_magnetization(2) =  \n')
        file.write('    starting_magnetization(3) =  \n')
        file.write('    starting_magnetization(4) =  \n')
        file.write(' /\n')
        file.write(' &electrons\n')
        file.write('    electron_maxstep = 1000\n')
        file.write('    conv_thr         = 1.0D-6\n')
        file.write('    mixing_mode      = \'local-TF\'\n')
        file.write('    mixing_beta      = 0.7D0\n')
        file.write('    mixing_ndim      = 8\n')
        file.write('    diagonalization  = \'cg\'\n')
        file.write('    diago_david_ndim = 4\n')
        file.write('    startingwfc      = \'atomic+random\'\n')
        file.write('    adaptive_thr     = .TRUE.\n')
        file.write(' /\n')
        file.write(' &ions\n')
        file.write('    ion_dynamics      = \'bfgs\'\n')
        file.write('    pot_extrapolation = \'atomic\'\n')
        file.write('    wfc_extrapolation = \'none\'\n')
        file.write(' /\n')
        file.write(' &cell\n')
        file.write('    cell_dynamics  =  \'bfgs\'\n')
        file.write('    cell_dofree    =  \'all\'\n')
        file.write(' /\n')
        file.write(' ATOMIC_SPECIES\n')
        file.write(' ATOMIC_POSITIONS (angstrom)\n')
        file.write(' K_POINTS automatic\n')
